# Site settings
title: Visualization Design Lab
email: vdl-faculty@sci.utah.edu
description: "Data visualization research lab at SCI, SoC, University of Utah"
baseurl: ""
url: "http://vdl.sci.utah.edu"
twitter_username:
github_username: visdesignlab
youtube_username:
facebook_page:
safe: false
lsi: false
google_analytics: "'UA-69348306-1'"
use_analytics: true

paper_content_url: http://sci.utah.edu/~vdl/papers/

gems:
  - jekyll-redirect-from

# Build settings
permalink: pretty
sass:
  sass_dir: _sass
# exclude from build
exclude: ["README.md", ".idea/"]

# Collections
collections:
  persons:
    output: true
  publications:
    output: true
  thesis:
    output: true
  videos:
    output: false
  institutions:
    output: false
  funding:
    output: false
  talks:
    output: false

